.PHONY: all

all: 
	DEFMT_LOG=info cargo build 
clean: 
	DEFMT_LOG=info cargo clean
run: 
	DEFMT_LOG=info cargo run
led: 
	DEFMT_LOG=info cargo run --bin led
i2c: 
	DEFMT_LOG=info cargo run --bin i2c
cam: 
	DEFMT_LOG=info cargo run --bin cam
sd: 
	DEFMT_LOG=info cargo run --bin sd
