name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: thumbv8m.main-none-eabihf
          components: rustfmt, clippy, llvm-tools-preview

      - name: Install tools (just, cargo-llvm-cov)
        uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-llvm-cov

      - name: Run CI suite
        run: just ci

